# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: stevengogogo4321@gmail.com
julia:
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - arch: x86
      os: osx
  include:
     - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
