name    = "FindSteadyStates"
uuid    = "5ce5e58b-649a-467a-bfd0-ccefe064e451"
authors = ["Steven Chiu <stevengogogo4321@gmail.com> and contributors"]
version = "0.3.1"

[deps]
  DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
  LinearAlgebra         = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
  ModelingToolkit       = "961ee093-0014-501f-94e3-6117800e7a78"
  Parameters            = "d96e819e-fc66-5662-9728-84c9c7592b0a"
  Random                = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
  DifferentialEquations = "6, 7"
  ModelingToolkit       = "6, 7, 8"
  Parameters            = "0.12"
  julia                 = "1.6, 1.7"

[extras]
  CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
