name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_NUM_THREADS: 2

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["1.6", "1.7"]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1.2.0
      - uses: julia-actions/julia-runtest@v1.7.0
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2.1.0
        with:
          files: lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sympy scipy numpy matplotlib
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      # - name: Configure Git
      #   run: |
      #     git config --global "$(git log -n 1 --pretty=format:%an)"
      #     git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
      #     git config --global github.user ${{ github.actor }}
      - name: Install current working package
        shell: julia --project=docs --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
      - name: Doc Test
        shell: julia --project=docs --color=yes {0}
        run: |
          using Documenter: doctest
          using FindSteadyStates
          doctest(FindSteadyStates)
      - name: Generate document
        run: julia --project=docs --color=yes docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
